export const LANGUAGE_VERSIONS = {
  javascript: "18.15.0",
  typescript: "5.0.3",
  c: "10.2.0",
  cpp: "10.2.0",
  python: "3.10.0",
  java: "15.0.2",
  csharp: "6.12.0",
  php: "8.2.3",
  ruby: "3.0.1",
  go: "1.16.2",
  rust: "1.68.2",
  swift: "5.3.3",
  dart: "2.19.6",
  kotlin: "1.8.20",
  python2: "2.7.18",
  elixir: "1.11.3",
  groovy: "3.0.7",
  pascal: "3.2.2",
  swift: "5.3.3",
};

export const CODE_SNIPPETS = {
  javascript: `\nfunction greet(name) {\n\tconsole.log("Hello, " + name + "!");\n}\n\ngreet("Alex");\n`,
  typescript: `\ntype Params = {\n\tname: string;\n}\n\nfunction greet(data: Params) {\n\tconsole.log("Hello, " + data.name + "!");\n}\n\ngreet({ name: "Alex" });\n`,
  c: `#include <stdio.h>\n\nint main() {\n\tprintf("Hello, World!\\n");\n\treturn 0;\n}\n`,
  cpp: `#include <iostream>\n\nint main() {\n\tstd::cout << "Hello, World!" << std::endl;\n\treturn 0;\n}\n`,
  python: `\ndef greet(name):\n\tprint("Hello, " + name + "!")\n\ngreet("Alex")\n`,
  java: `\npublic class HelloWorld {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println("Hello World");\n\t}\n}\n`,
  csharp:
    'using System;\n\nnamespace HelloWorld\n{\n\tclass Hello { \n\t\tstatic void Main(string[] args) {\n\t\t\tConsole.WriteLine("Hello World in C#");\n\t\t}\n\t}\n}\n',
  php: "<?php\n\n$name = 'Alex';\necho $name;\n",
  ruby: `def greet(name)\n\tputs "Hello, #{name}!"\nend\n\ngreet("Alex")\n`,
  go: `package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello, World!")\n}\n`,
  rust: `fn main() {\n\tprintln!("Hello, World!");\n}\n`,
  swift: `func greet(name: String) {\n\tprint("Hello, \\(name)!")\n}\n\ngreet(name: "Alex")\n`,
  dart: `void main() {\n\tprint('Hello, World!');\n}\n`,
  kotlin: `fun main() {\n\tprintln("Hello, World!")\n}\n`,
  python2: `print "Hello, World!"\n`,
  elixir: `defmodule Hello do\n  def hello(name) do\n    IO.puts "Hello, #{name}!"\n  end\nend\n\nHello.hello("Alex")\n`,
  groovy: `println 'Hello, World!'\n`,
  cobol: `       IDENTIFICATION DIVISION.\n       PROGRAM-ID. Hello.\n       PROCEDURE DIVISION.\n           DISPLAY "Hello, World!".\n       STOP RUN.\n`,
};

// export const LANGUAGES = [
//   "javascript",
//   "typescript",
//   "python",
//   "java",
//   "csharp",
//   "php",
//   "ruby",
//   "go",
//   "rust",
//   "swift",
//   "c",
//   "cpp",
//   "dart",
//   "perl",
//   "raku",
//   "kotlin",
//   "lua",
//   "haskell",
//   "julia",
//   "coffeescript",
//   "csharp_net",
//   "fsharp_net",
//   "basic_net",
//   "python2",
//   "elixir",
//   "emacs",
//   "erlang",
//   "forth",
//   "freebasic",
//   "groovy",
//   "nasm",
//   "nim",
//   "ocaml",
//   "octave",
//   "ponylang",
//   "prolog",
//   "pure",
//   "powershell",
//   "rscript",
//   "racket",
//   "ruby",
//   "scala",
//   "sqlite3",
//   "vlang",
//   "zig",
//   "bash",
//   "befunge93",
//   "bqn",
//   "brachylog",
//   "brainfuck",
//   "cjam",
//   "clojure",
//   "cobol",
//   "cow",
//   "crystal",
//   "dash",
//   "fsi",
//   "dragon",
//   "file",
//   "forte",
//   "golfscript",
//   "husk",
//   "iverilog",
//   "japt",
//   "jelly",
//   "lisp",
//   "llvm_ir",
//   "lolcode",
//   "paradoc",
//   "pascal",
//   "pyth",
//   "raku",
//   "retina",
//   "rockstar",
//   "rscript",
//   "ruby",
//   "samarium",
//   "smalltalk",
//   "vyxal",
//   "yeethon",
//   "zig"
// ];



